### ISSUE TITLE
How to build the project locally?

### ISSUE THREAD

**Issue by DomenPigeon** [maraf/dotnet-wasm-react#2]
I would like to thank you for this example which really looks intersting and exiting. But I struggle a bit how to build it locally.

Could you please just add some instructions into the readme file, what I need to do in order to build and run it locally?

Thanks 😃

**Comment by maraf** [comment]
Sorry for the late reply. I opened a PR with the description #4.
Let me know if it works for you.

**Comment by DomenPigeon** [comment]
Thanks for the response :) 
After doing everything you have written in the docs and the running `npm run start` in the app folder I still get this error:
![image](https://user-images.githubusercontent.com/35853390/201467547-464155e0-90da-453a-b1b3-386ba2bdd7e5.png)

Also in the app folder I don't see any compiled C# assemblies. You mentin a `postbuild` script. Is this a file or just some configuration? Because I coudn't find any such file.
